<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCX4Sza4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCX4Sza4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCX4Sza4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCX4Sza4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCX4Sza4\App_KernelDevDebugContainer([
    'container.build_hash' => 'CX4Sza4',
    'container.build_id' => '092ae150',
    'container.build_time' => 1747127918,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCX4Sza4');
